#!/bin/bash

#This is a script analyzing basic server performance stats

#Function to check package manager & install sysstat
check_pkg_manager_install_sysstat() {
    #Debian
    if command -v apt > /dev/null; then
        sudo apt update && sudo apt install sysstat -y
    #RHEL
    elif command -v dnf > /dev/null; then
        sudo dnf install sysstat -y
    #Arch
    elif command -v pacman > /dev/null; then
        sudo pacman -S sysstat --noconfirm
    #OpenSuse
    elif command -v zypper > /dev/null; then
        sudo zypper install -y sysstat
    #Older RHEL
    elif command -v yum > /dev/null; then
        sudo yum install sysstat -y
    else
    echo 'Error: Supported package like  (apt, dnf, pacman, yum or zypper) manager not found'
    exit 1
fi
}

#If mpstat is not installed, install using system's package manager
if ! command -v mpstat &> /dev/null; then
    check_pkg_manager_install_sysstat
fi

#Displaying total CPU usage
echo -e "\n +++++++++++++++++++++++++++++++++++ Total CPU Usage +++++++++++++++++++++++++++++++++++\n"
mpstat