#!/bin/bash

#This is a script analyzing basic server performance stats

# +++++++++++++++++++++++++++++++++++ Total CPU usage +++++++++++++++++++++++++++++++++++
#Function to check package manager & install sysstat
check_pkg_manager_install_sysstat() {
    #Debian
    if command -v apt > /dev/null; then
        sudo apt update && sudo apt install sysstat -y
    #RHEL
    elif command -v dnf > /dev/null; then
        sudo dnf install sysstat -y
    #Arch
    elif command -v pacman > /dev/null; then
        sudo pacman -S sysstat --noconfirm
    #OpenSuse
    elif command -v zypper > /dev/null; then
        sudo zypper install -y sysstat
    #Older RHEL
    elif command -v yum > /dev/null; then
        sudo yum install sysstat -y
    else
    echo 'Error: Supported package like  (apt, dnf, pacman, yum or zypper) manager not found'
    exit 1
fi
}

#If mpstat is not installed, install using system's package manager
if ! command -v mpstat &> /dev/null; then
    check_pkg_manager_install_sysstat
fi

#Displaying total CPU usage
echo -e "\n +++++++++++++++++++++++++++++++++++ Total CPU Usage +++++++++++++++++++++++++++++++++++\n"
mpstat

# Method 2: Read and extract CPU usage info from "/proc/stat" file

# +++++++++++++++++++++++++++++++++++ Total memory usage (Free vs Used including percentage) +++++++++++++++++++++++++++++++++++
echo -e "\n +++++++++++++++++++++++++++++++++++ Total Memory Usage +++++++++++++++++++++++++++++++++++\n"
# All memory stats of the linux system is stored in this file => /proc/meminfo
# Extracting the needed memory usage data as needed from file
freeMemory=$(grep MemFree /proc/meminfo)
totalMemory=$(grep MemTotal /proc/meminfo)
# usedMemory=($totalMemory-$freeMemory)
echo $freeMemory
echo $totalMemory