#!/bin/bash

# END just outputs whatever you tell it to at the very end of the page/file, in this case, total users of all servers
# first we filter online servers only
# then we print those online servers only
# then we calculate all the server users contained in column 4 and assign the total to variable all_servers_users
# then at the end print a string with the total number of server users calculated before
awk '$2 == "online" { print } { all_servers_users += $4 } END { print "\n Total number of users on all our servers is: " all_servers_users "\n" }' servers.txt

# To calculate users in online servers only, add the calculation logic to the same print sorted online servers curly brackets
# BEGIN here is just adding a line break for beauty purposes in output
awk 'BEGIN { print "\n"  } $2 == "online" { print $0; all_online_users += $4 } END { print "\nTotal Online Users: ", all_online_users, "\n" }' servers.txt
