#!/bin/bash

echo "--------------------------------------------"
echo "Welcome Sys Admin! Here are the server stats"
echo "--------------------------------------------"

# Color variables
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# +++++++++++++++++++++++++++++++++++++++++++++++ CPU USAGE +++++++++++++++++++++++++++++++++++++++++++++++
# Reading and extract CPU usage info from "/proc/stat" file
# read first batch idleCPUTime and totalCPUusageTime stats
# in awk: i grab the line with the cpu filter, to get the average stats of all cpu cores...
# ... calculate the total cpu usage time by adding columns 2-9 ...
# ... and then including this total as part of the output with the other cpu stat columns to be read
# in read: read stores all the cpu stat columns in array (cpu_time_stats) ...
# ... and I fetch the cpu_time_stats and total_cpu_usage_time1 from cpu_time_stats array
read -a cpu_time_stats < <(awk '$1 == "cpu" {
	total_cpu_time = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9;
	print $2, $3, $4, $5, $6, $7, $8, $9, total_cpu_time
}' /proc/stat)
cpu_idle_time1=${cpu_time_stats[3]}
total_cpu_usage_time1=${cpu_time_stats[8]}
# echo -e "cpu_idle_time1: $cpu_idle_time1 : total_cpu_usage_time1: $total_cpu_usage_time1\n"

# sleep
sleep 1

# read second batch idleCPUTime and totalCPUusageTime stats
read -a cpu_time_stats2 < <(awk '$1 == "cpu" {
	total_cpu_time = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9;
	print $2, $3, $4, $5, $6, $7, $8, $9, total_cpu_time
}' /proc/stat)
cpu_idle_time2=${cpu_time_stats2[3]}
total_cpu_usage_time2=${cpu_time_stats2[8]}
# echo -e "cpu_idle_time2: $cpu_idle_time2 : total_cpu_usage_time2: $total_cpu_usage_time2\n"

# find the differences in batch 1 and 2
(( diff_idle_cpu_time = cpu_idle_time2 - cpu_idle_time1  ))
(( diff_total_cpu_time = total_cpu_usage_time2 - total_cpu_usage_time1  ))
# echo "diff_idle_cpu_time: $diff_idle_cpu_time : diff_total_cpu_time: $diff_total_cpu_time"

# -v flag in awk: creates an awk variable and assigns the variables we calculated above in the bash script
# the calculation happens in the BEGIN clause => total_time - idle_time = actual usage_time ...
# ... usage_time / total-time * 100 gets the percentage of the actual usage time of the CPU
cpu_usage_percent=$(
	awk -v idle="$diff_idle_cpu_time" -v total="$diff_total_cpu_time" 'BEGIN {printf "%.2f", (total - idle) / total * 100}'
)
# echo -e "\n--- CPU Usage ---"
echo -e "\nTotal CPU Usage: ${GREEN}$cpu_usage_percent%${NC}\n"

# +++++++++++++++++++++++++++++++++++++++++++++++ MEMORY USAGE +++++++++++++++++++++++++++++++++++++++++++++++
awk '
	# function that converts fetched memory data from kbs to more readable sizes
	# unlike printf, sprintf returns a formatted string instead of printing it
	function convert_mem(mem) {
		if (mem >= 1048576){
			#  convert memory to GB
			return sprintf("%.2f GB", mem/1048576)
		} else if (mem >= 1024){
			#  convert memory to MB
			return sprintf("%.2f MB", mem/1024)
		} else {
			return sprintf("%d KB", mem)
		}
	}

	# BEGIN { print "\n--- Memory Usage ---\n" }
	
	# grabbing total and available memory from file
	$1 == "MemTotal:" { total_mem=$2 }
	$1 == "MemAvailable:" { avilable_mem=$2 }
	END { 
		# calculating used memory
		memory_used = total_mem - avilable_mem
		# printing out the data fetched
		printf "Memory Used: %s (%d%%)\nAvailable Memory: %s (%d%%)\n",
		 convert_mem(memory_used), (memory_used/total_mem)*100, convert_mem(avilable_mem), (avilable_mem/total_mem)*100
	}
' /proc/meminfo

echo -e "\n"

# +++++++++++++++++++++++++++++++++++++++++++++++ DISK USAGE +++++++++++++++++++++++++++++++++++++++++++++++
# df categories: $1: filesystem, $2: 1K-blocks, $3: Used, $4: Available, $5: Use Percentage and $6: Mounted on
# filter out only physical drives => drives starting with /dev/ are physical drives, this is what we want
# -k deliveres space in KBs
# grep '^/dev/': ^ means start of a line. so look for filesystems with the name dev at the start and not anywhere else
df -k | grep '^/dev/' | awk '
# BEGIN { print "\n--- Disk Usage ---\n" }
{
	total_space += $2;
	used_space += $3;
	free_space += $4
}
END {
	# converting from KB to GB
	total_space_gb = total_space / 1048576
	used_space_gb = used_space / 1048576
	free_space_gb = free_space / 1048576

	# calculating percentage
	used_space_pct = (used_space / total_space) * 100
	free_space_pct = (free_space / total_space) * 100

	printf "Total space: %.2fGB\nUsed space: %.2fGB (%.1f%%)\nFree space: %.2fGB (%.1f%%)\n",
	 total_space_gb, used_space_gb, used_space_pct, free_space_gb, free_space_pct
}
'

# +++++++++++++++++++++++++++++++++++++++++++++++ Top 5 High CPU Usage Processes +++++++++++++++++++++++++++++++++++++++++++++++
# fetching the 5 linux processes with the highest CPU usage
# ps flags => -e: displays all processes; -o: let's you customize fields you want ps to fetch by ...
# ... like pcpu(cpu percentage), pid (process id), comm (command/process name)...
# ... --sort is for sorting the data ps fetched. --sort=-pcpu: sort cpu percentage by descending order (the '-' means descending order)
echo -e "\n--- Top 5 High CPU Usage Processes ---\n"
ps -eo pcpu,pid,comm --sort=-pcpu | head -n 6 | column -t

# +++++++++++++++++++++++++++++++++++++++++++++++ Top 5 High Memory Usage Processes +++++++++++++++++++++++++++++++++++++++++++++++
# fetching the 5 linux processes with the highest CPU usage
echo -e "\n--- Top 5 High Memory Usage Processes ---\n"
ps -eo pmem,pid,comm --sort=-pmem | head -n 6 | column -t