#!/bin/bash

sudo apt update && sudo apt upgrade -y
sudo apt install -y python3 python3-pip
echo -e "\e[32mPython and pip were successfully installed\e[0m"
echo -e "\e[32mPython version:\e[0m $(python3 --version)"
echo -e "\e[32mPip version:\e[0m $(pip3 --version)"