#!/bin/bash

# +++++++++++++++++++++++++++++++++++++++++++++++ CPU USAGE +++++++++++++++++++++++++++++++++++++++++++++++

# Reading and extract CPU usage info from "/proc/stat" file
# read first batch idleCPUTime and totalCPUusageTime stats
# in awk: i grab the line with the cpu filter, to get the average stats of all cpu cores...
# ... calculate the total cpu usage time by adding columns 2-9 ...
# ... and then including this total as part of the output with the other cpu stat columns to be read
# in read: read stores all the cpu stat columns in array (cpu_time_stats) ...
# ... and I fetch the cpu_time_stats and total_cpu_usage_time1 from cpu_time_stats array
read -a cpu_time_stats < <(awk '$1 == "cpu" {
	total_cpu_time = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9;
	print $2, $3, $4, $5, $6, $7, $8, $9, total_cpu_time
}' /proc/stat)
cpu_idle_time1=${cpu_time_stats[3]}
total_cpu_usage_time1=${cpu_time_stats[8]}
# echo -e "cpu_idle_time1: $cpu_idle_time1 : total_cpu_usage_time1: $total_cpu_usage_time1\n"

# sleep
sleep 1

# read second batch idleCPUTime and totalCPUusageTime stats
read -a cpu_time_stats2 < <(awk '$1 == "cpu" {
	total_cpu_time = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9;
	print $2, $3, $4, $5, $6, $7, $8, $9, total_cpu_time
}' /proc/stat)
cpu_idle_time2=${cpu_time_stats2[3]}
total_cpu_usage_time2=${cpu_time_stats2[8]}
# echo -e "cpu_idle_time2: $cpu_idle_time2 : total_cpu_usage_time2: $total_cpu_usage_time2\n"

# find the differences in batch 1 and 2
(( diff_idle_cpu_time = cpu_idle_time2 - cpu_idle_time1  ))
(( diff_total_cpu_time = total_cpu_usage_time2 - total_cpu_usage_time1  ))
# echo "diff_idle_cpu_time: $diff_idle_cpu_time : diff_total_cpu_time: $diff_total_cpu_time"

# -v flag in awk: creates an awk variable and assigns the variables we calculated above in the bash script
# the calculation happens in the BEGIN clause => total_time - idle_time = actual usage_time ...
# ... usage_time / total-time * 100 gets the percentage of the actual usage time of the CPU
cpu_usage_percent=$(
	awk -v idle="$diff_idle_cpu_time" -v total="$diff_total_cpu_time" 'BEGIN {printf "%.2f", (total - idle) / total * 100}'
)
echo -e "\n+++++++++++++++++++++++++++++++++++++++++++++++ CPU USAGE +++++++++++++++++++++++++++++++++++++++++++++++\n"
echo "Total CPU Usage: $cpu_usage_percent%"

# +++++++++++++++++++++++++++++++++++++++++++++++ MEMORY USAGE +++++++++++++++++++++++++++++++++++++++++++++++
# Reading /proc/meminfo file to fetch memory stats
# free memory
# grep returns data in this format: MemFree: 6429012 kB, but I only need the memory data hence the read code below
# _ mem_free _ => _ is MemFree texr, mem_used is actual memory data and _ is memory size 'kb' text
echo -e "\n+++++++++++++++++++++++++++++++++++++++++++++++ MEMORY USAGE +++++++++++++++++++++++++++++++++++++++++++++++\n"
read _ mem_free _ < <(grep 'MemFree' /proc/meminfo)
echo "Free Memory: $mem_free kbs"
# fetching total memory
read _ total_mem _ < <(grep 'MemTotal' /proc/meminfo)
echo "Total Memory: $total_mem kbs"
# used memory
(( mem_used=total_mem-mem_free ))
echo "Used Memory: $mem_used kbs"
# memory percentage