name: Using variables and secrets
on: push
env: # environment variables used in whole workflow by multiple jobs
  DOCKER_USER: ${{ vars.MY_NAME }} # repository variable
  DOCKER_IMAGE_NAME: springboot-api
  DOCKER_REGISTRY: docker.io

jobs:
  docker_build_login_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo "docker build -t $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_IMAGE_NAME:latest"

      - name: Docker login
        env:
          DOCKER_PASSWD: ${{ secrets.TEST_DOCKER_PASSWD }} # repo secret used in this step only
        run: echo "docker login --username=$DOCKER_USER --password=$DOCKER_PASSWD"

      - name: Docker push
        run: echo "docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_IMAGE_NAME:latest"

  docker_deploy:
    needs: docker_build_login_and_publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        env:
          DOCKER_PORT: 8080:80 # environment variable used in this step only
        run: echo "docker run -d -p $DOCKER_PORT $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_IMAGE_NAME:latest"

# ---------- Notes on repo secrets & variables ----------
# 'in the project repo' navigate to 'settings -> secrets and variables -> actions'
# set any repository level secrets and variables here
# repository level secrets and variables can be accessed by any workflow in this repo across all branches
# secrets are for passwords, api keys etc
# variables are for global non-sensitive reusable variables like username etc

# ---------- repository secrets usage in workflows ----------
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets
# syntax -> ${{ secrets.YOUR_SECRET_VARIABLE_HERE }}
# for security, assign the secret to an environment variable and then pass the env variable for usage
# example:     env:
#                 SUPER_SECRET: ${{ secrets.MYPASSWD }}
#              run: echo "docker login --username=$DOCKER_USER --password=$SUPER_SECRET"

# ---------- repository variables usage in workflows ----------
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-variables
# syntax -> ${{ vars.YOUR_VARIABLE_NAME_HERE }}
# example1: docker build -t $DOCKER_REGISTRY/${{ vars.MY_NAME }}/$DOCKER_IMAGE_NAME:latest
# example2:    env:
#                 DOCKER_USER: ${{ vars.MY_NAME }}
#              run: echo "docker login --username=$DOCKER_USER --password=$SUPER_SECRET"